[package]
name = "camera_live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.80"
qhyccd_sdk = { path = "../qhyccd_sdk" }